; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = endpoint_pod

[env]
platform = espressif32
board = heltec_wireless_tracker
framework = arduino
monitor_speed = 115200
platform_packages = 
	framework-arduinoespressif32 @ ^3
board_build.variants_dir = variants
board_build.partitions = default_8MB.csv
upload_speed = 921600
upload_protocol = esptool
lib_deps = 
	bblanchon/ArduinoJson@^7.2.1
	knolleary/PubSubClient@^2.8
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MSC_ON_BOOT=0
	-DARDUINO_USB_DFU_ON_BOOT=0
	
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	
	-DREGION_AU915
	-DACTIVE_REGION=LORAMAC_REGION_AU915
	
	-DSLOW_CLK_TPYE=0
	-DLoRaWAN_DEBUG_LEVEL=0
	-DLORAWAN_PREAMBLE_LENGTH=8
	-DLORAWAN_DEVEUI_AUTO=0
	
	-DBOARD_HAS_PSRAM
	-DPROJECT_DEFAULT_HOP_LIMIT=3
	-DPROJECT_MAX_HOP_OVERRIDE=5

[env:endpoint_pod]
build_flags = 
	${env.build_flags}
	-DNODE_PROFILE_ENDPOINT_POD
	-DPROJECT_NODE_PROFILE_NAME=\"ENDPOINT_POD\"

[env:relay_fixed]
build_flags = 
	${env.build_flags}
	-DNODE_PROFILE_RELAY_FIXED
	-DPROJECT_NODE_PROFILE_NAME=\"RELAY_FIXED\"

[env:gateway_central]
build_flags = 
	${env.build_flags}
	-DNODE_PROFILE_GATEWAY_CENTRAL
	-DPROJECT_NODE_PROFILE_NAME=\"GATEWAY_CENTRAL\"
